#!/bin/bash

# NOTE: this script will FULLY RUN minimization AND QMMM steps

# start of script-----------------------------------------------------------------------------------------


# source /software/loslab/activate.sh
# module add amber-14-ll


#-----------NEEDS TO BE SPECIFIED -------------------
LIG_ID=293      # This HAS to be the residue number!!!


TOP=`ls *.prmtop`
CRD=`ls *.inpcrd`

cp $CRD ref.crd # copy initial coordinates to reference
cat >> ./emin1.in <<EOF
# minimization with heavy atoms of complex restrained
 &cntrl
   imin=1,
   ntr=1,restraint_wt=500.0,restraintmask=':1-$LIG_ID & !(@H=)',
   ntpr=100, ntwx=100, igb=8

   maxcyc=1000, ncyc=500,
/
&gb
  igb=8, saltcon=0.100
/

EOF

cat >> ./emin2.in <<EOF
# minimization with restraints on backbone
 &cntrl
   imin=1,
   ntr=1,restraint_wt=100.0,restraintmask='@CA,C,N|(:TIP)@C1,C2,C3',
   ntpr=100, ntwx=100, igb=8

   maxcyc=1000, ncyc=500,

/
&gb
  igb=8, saltcon=0.100
/

EOF

cat >> ./emin3.in <<EOF
# minimization with restraints on backbone
 &cntrl
   imin=1,
   ntr=1,restraint_wt=50.0,restraintmask='@CA,C,N|(:TIP)@C1,C2,C3',
   ntpr=100, ntwx=100, igb=8

   maxcyc=1000, ncyc=500,

/
&gb
  igb=8, saltcon=0.100
/

EOF

cat >> ./emin4.in <<EOF
# minimization with restraints on backbone
 &cntrl
   imin=1,
   ntr=1,restraint_wt=25.0,restraintmask='@CA,C,N|(:TIP)@C1,C2,C3',
   ntpr=100, ntwx=100, igb=8

   maxcyc=1000, ncyc=500,

/
&gb
  igb=8, saltcon=0.100
/

EOF

cat >> ./emin5.in <<EOF
# minimization with restraints on backbone
 &cntrl
   imin=1,
   ntr=1,restraint_wt=1.0,restraintmask='@CA,C,N|(:TIP)@C1,C2,C3',
   ntpr=100, ntwx=100, igb=8

   maxcyc=1000, ncyc=500,

/
&gb
  igb=8, saltcon=0.100
/


EOF

